site_name: DigitalDamage Docs
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - toc.integrate
nav:
  - Home: index.md
  - Products:
      - FleetSense: fleetsense.md
      - SMTP-Intruder: smtp_intruder.md
      - GhostShell: ghostshell.md
      - AutoEX: autoex.md
      - Overview: products.md
  - Architecture: architecture.md
  - Company:
      - About: about.md
      - Contact: contact.md
